### ISSUE TITLE
Convert in-line manifests to linked manifests

### ISSUE THREAD

**Issue by zr-msft** [openservicemesh/osm-docs#115]
For example, this section:
https://docs.openservicemesh.io/docs/install/manual_demo/#create-pods-services-serviceaccounts

could use these files instead:
https://github.com/openservicemesh/osm/blob/release-v0.9/docs/example/manifests/apps/bookbuyer.yaml

**Comment by bridgetkromhout** [comment]
In the v0.8.x version of the manual demo, they were using linked manifests. They moved to inline for v0.9.x, so the first question would be to find out why. 

The other thing to keep in mind is that linking to `main` is inherently unpredicatable. We will only be safe linking to a released branch; otherwise there is a high probability the manifest could drift and become incorrect over time. (This may be _why_ this change happened, or it may be a coincidence.)

**Comment by zr-msft** [comment]
thank you @bridgetkromhout 

intention was to used versioned manifests, but pasted the wrong link. Good catch
