### ISSUE TITLE
Files hierarchy is not correct for files in traffic_management/demos

### ISSUE THREAD

**Issue by shashankram** [openservicemesh/osm-docs#49]
The `*_demo.md` files in `content/docs/tasks_usage/traffic_management/demos/` are not displayed under the `Traffic Management Demos` section, but rather under the `Traffic Management` top level section.

Based on the folder structure, I would expect the `*_demo.md` files to show up under an intermediary `Traffic Management Demos` folder instead.

![image](https://user-images.githubusercontent.com/21697719/118559843-6ae10b00-b71d-11eb-81d5-93c124c53ef5.png)

**Comment by bridgetkromhout** [comment]
There is an _index.md file (https://github.com/openservicemesh/osm-docs/blob/main/content/docs/tasks_usage/traffic_management/demos/_index.md) but I wonder if this is too many levels deep - @flynnduism to advise.

**Comment by flynnduism** [comment]
This looks like a stylesheet issue rather than a Hugo / templating issue. The sidebar is rendering the `*_demo.md` pages as children of the `Traffic Management Demos` page, but the CSS incorrectly makes it look like they are siblings. 

<img width="750" alt="Screen Shot 2021-05-17 at 3 27 19 PM" src="https://user-images.githubusercontent.com/686194/118564243-d4184c80-b724-11eb-8191-9924f8bccbae.png">

I will review the styling to ensure that 3rd level items and 4th level items can be properly distinguished in the tree. My changes in #44 made things clearer for the upper levels, but looks like there's more styling needed.

**Comment by jaellio** [comment]
@flynnduism can you give an update on this issue? Thank you!

**Comment by zr-msft** [comment]
This no longer appears to be an issue. Closing
